default_settings: null
behaviors:
  Pilot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 131072
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play: null
    behavioral_cloning: null
    framework: pytorch
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  num_waypoints:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1461
          value: 1.0
      name: Lesson0
      completion_criteria:
        behavior: Pilot
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.2
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1462
          value: 2.0
      name: Lesson1
      completion_criteria:
        behavior: Pilot
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.4
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1463
          value: 3.0
      name: Lesson2
      completion_criteria:
        behavior: Pilot
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.6
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1464
          value: 4.0
      name: Lesson3
      completion_criteria: null
  goal_size:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1465
          value: 0.45
      name: Lesson0
      completion_criteria:
        behavior: Pilot
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.1
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1466
          value: 0.35
      name: Lesson1
      completion_criteria:
        behavior: Pilot
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.2
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1467
          value: 0.25
      name: Lesson2
      completion_criteria:
        behavior: Pilot
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.4
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1468
          value: 0.15
      name: Lesson3
      completion_criteria:
        behavior: Pilot
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.6
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1469
          value: 0.05
      name: Lesson4
      completion_criteria: null
checkpoint_settings:
  run_id: curriculumV2_tagVelocity_velocityPenalty
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
debug: false
